services:
  mysql:
    image: mysql:8.0                # 8.4 dropped the flag we need
    container_name: goviral_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    
    # ── health-check ───────────────────────────────────────
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    # ───────────────────────────────────────────────────────

    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: goviral_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: "StrongDevPass#2025"     # literal # is fine here
    ports:
      - "3308:3306"                 # host 3308 → container 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - goviral-net

  web:
    build: .
    container_name: goviral_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # inside Docker we hit the DB by service-name + 3306
      DATABASE_URL: "mysql://dev_user:StrongDevPass%232025@mysql:3306/goviral_db"
    depends_on:
      - mysql
    networks:
      - goviral-net

volumes:
  mysql_data:

networks:
  goviral-net:
