version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: goviral_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goviral_db
    ports:
      - "3308:3306"  # Host:Container (avoid conflict with your local MySQL)
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - goviral-net

  web:
    build: .
    container_name: goviral_web
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/goviral_db
    depends_on:
      - mysql
    networks:
      - goviral-net

volumes:
  mysql_data:

networks:
  goviral-net:
